### ISSUE TITLE
V490: No response from device

### ISSUE THREAD

**Issue by biji** [openpst/openpst#2]
Tried to revive my old tablet (LG V490), entered 9008 dload mode (press up+down while boot)

[57516.710926] usb 2-3: New USB device found, idVendor=05c6, idProduct=9008
[57516.710931] usb 2-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[57516.710934] usb 2-3: Product: QHSUSB__BULK
[57516.710937] usb 2-3: Manufacturer: Qualcomm CDMA Technologies MSM
[57516.712252] qcserial 2-3:1.0: Qualcomm USB modem converter detected
[57516.712585] usb 2-3: Qualcomm USB modem converter now attached to ttyUSB0

Try to connect using sahara, connected, but all command failed like *Read serial number* always return _No response form device_
Kindly need help thanks

**Comment by ghassani** [comment]
Please build the debug version and attach the GUI text log as well as the program stdout data from your terminal so I can see what might be going on.

Also, please re-open the issue in the appropriate repository `openpst/sahara`. I am closing this issue.

Usually 9008 mode is entered automatically if critical system programs are not loaded, like sbl1 for example. If you have to force it into 9008 with some button combo, it could be loaded from sbl1 or some other partition if LG customized it that way instead of PBL like it would automatically if it failed to load something. And of course, OEMs can build the SoC as they see fit, removing things they might not need or want that are not system critical. If you are able to connect and get past the hello portion, try sending the requested image and continue on to restore the device. Reading client commands isn't required to send a loader/image.

**Comment by ghassani** [comment]
Try these steps to send client commands:

- Restart device to 9008
- Open Sahara program
- Uncheck Auto Hello
- Connect to the device
- It should automatically read the hello from the device, if not press the Read Hello button.
- Set Mode in the Hello Handshake section to Client Command Mode
- Click the Respond button in the Hello Handshake section
- Go to Command tab if it does not take you there automatically
- Send a client command
